#!/usr/bin/env bash
# Transfer a file from src to dest
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

src="$1"
IP="$2"
username="$3"
path_ssh="$4"

if (($#<4))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$path_ssh" "$src" "$username"@"$IP:~/"

fi
