#!/usr/bin/env bash
# This script displays "To infinity and beyond indefinitely"
# It adds ``sleep 2`` in between each iteration,
#+ add displays "I am invincible!!!" when receiving a `SIGTERM` signal

trap 'echo "I am invincible!!!"' SIGTERM
while 'true'
do
    echo "To infinity and beyond"
    sleep 2
done
